# Generated by Django 2.1.5 on 2019-03-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='building',
            new_name='building_name',
        ),
    ]
