# Generated by Django 2.1.5 on 2019-03-21 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0002_auto_20190320_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tower', to='building_app.Building'),
        ),
    ]
