# Generated by Django 2.1.5 on 2019-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0003_auto_20190321_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='extras',
            field=models.CharField(choices=[('JCZ', 'jacuzzi'), ('SAU', 'suana'), ('STU', 'studio')], default='STU', max_length=3),
        ),
    ]
