# Generated by Django 2.1.5 on 2019-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0005_auto_20190325_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='extras',
            field=models.CharField(choices=[('jacuzzi', 'jacuzzi'), ('sauna', 'sauna'), ('studio', 'studio')], default='studio', max_length=10),
        ),
    ]
