# Generated by Django 2.1.5 on 2019-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_app', '0009_auto_20190328_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchclock',
            name='person',
            field=models.ForeignKey(null=True, on_delete='models.CASACADE', related_name='the_person', to='building_app.Person'),
        ),
    ]
